---
- name: use reverse SSH to connect to SDN GW
  hosts: 127.0.0.1
  connection: local

  tasks:
 #        - name: "Kill previous sessions on local port"
 #          shell: ps axuf | grep 2222 | grep ssh | awk '{print "kill -9 " $1}'

         - name: Create SSH tunnel
           shell: ssh -p 10022 root@localhost -i /root/.ssh/id_rsa


