---
- name: configure VXLAN between two SDN Gateways
  hosts: 10.1.145.195
  become: true

  tasks:

  - name: create a vxlan interface for ovs-vxlan
    openvswitch_port:
      bridge: ovs-vxlan
      port: vxlan300
      state: present
      set: Interface vxlan300 type=vxlan options:remote_ip=10.1.145.196 options:key=300


- name: configure VXLAN between two SDN Gateways
  hosts: 10.1.145.196
  become: true

  tasks:

  - name: create a vxlan interface for ovs-vxlan
    openvswitch_port:
      bridge: ovs-vxlan
      port: vxlan300
      state: present
      set: Interface vxlan300 type=vxlan options:remote_ip=10.1.145.195 options:key=300
