---
- name: configure VXLAN between two SDN Gateways
  hosts: "{{sdngatewayA}}"
  become: true

  tasks:

  - name: create a vxlan interface for ovs-vxlan
    openvswitch_port:
      bridge: ovs-vxlan
      port: "{{vxlanid}}"
      state: present
      set: Interface "{{vxlanid}}" type=vxlan options:remote_ip="{{sdngatewayB}}" options:key="{{vxlanid}}"


- name: configure VXLAN between two SDN Gateways
  hosts: "{{sdngatewayB}}"
  become: true

  tasks:

  - name: create a vxlan interface for ovs-vxlan
    openvswitch_port:
      bridge: ovs-vxlan
      port: "{{vxlanid}}"
      state: present
      set: Interface "{{vxlanid}}" type=vxlan options:remote_ip="{{sdngatewayA}}" options:key="{{vxlanid}}"
