---
- name: deploy configure and start collectd
  hosts: tunnel
  become: true

  tasks:
  - name: deploy collectd software package on sdn gateway
    yum:
      state: latest
      name: epel-release
