---
- name: deploy configure and start VNF
  hosts: "{{server}}"
  vars:
    server: "you didn't specify a server"
  become: true

  tasks:

  - name: create Riverbed VNF with agent
    command: > 
        virsh create /ANSIBLE/riverbed-vnf-file.xml

  - name: start the monitoring agent for the aruba VNF
    command: sh /var/log/riverbed-vnf-agent.sh 
    async: 31536000
    poll: 0

