---
- name: deploy configure and start VNF
  hosts: "{{server}}"
  vars:
    server: "you didn't specify a server"
  become: true

  tasks:

  - name: create Cisco CSR
    command: >
        virsh create /ANSIBLE/csr-vnf-ansible-file.xml

  - name: start the monitoring agent for Cisco CSR
#    command: >
#        nohup /bin/sh /var/log/cisco-vnf-agent.sh &
    command: sh /var/log/cisco-vnf-agent.sh 
    async: 31536000
    poll: 0

